name: carsharing-app
services:
  carsharing-api:
    image: carsharing-api:latest
    ports:
      - "2137:8080"
  message-manager:
    image: rabbitmq:3-management
    ports:
      - "9000:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password


